version: "3"

# Define services
services:
  # App Service
  app:
    # Configuration for building the docker image for the service
    image: 'dcard-backend'
    container_name: 'server-container'  
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    volumes:
      - .:/code # 把當前資料夾 mount 掛載進去 container，這樣你可以直接在本地端專案資料夾改動檔案，container 裡面的檔案也會更動也不用重新 build image！
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    links:
      - redis
    depends_on:
      - redis
 
  redis:
    image: "redis:alpine" # 從 Docker Hub registry 來的 image
    container_name: 'redis' 
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  backend:
    driver: bridge

    
    